#pragma kernel CountVisiblePixels

Texture2D<float4> occludedTexture;
RWStructuredBuffer<int> numVisiblePixels;

[numthreads(32,32,1)]
void CountVisiblePixels(uint3 dispatchID : SV_DispatchThreadID)
{
    if(occludedTexture[dispatchID.xy].x != 0)
    {
        uint id = dispatchID.x + dispatchID.y * 32 * 32;
        int count = numVisiblePixels.IncrementCounter();
        numVisiblePixels[id] = count;
    }
}
